# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='suranme',
            new_name='surname',
        ),
    ]
