# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20170903_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='hobbies',
            field=models.ManyToManyField(to='main_app.Hobbies'),
        ),
    ]
