# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170903_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_persons_children_+', to='main_app.Persons'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='hobbies',
            field=models.ManyToManyField(to='main_app.Hobbies'),
        ),
    ]
