# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20170903_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_places',
            name='full_info',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='persons',
            name='hobbies',
            field=models.ManyToManyField(to='main_app.Hobbies'),
        ),
    ]
